# Generated by Django 3.1.4 on 2021-02-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
